#' "Mulistaged Penalty" constraint handling method for MOEA/D
#' 
#'  Constraint component of MOEA/D that uses multiple static penalty coefficients based
#'  on the unfeasibility of the solution proposed by Homaifar, Lai and Qi
#'
#' This routine implements a CHT that has 4 different stages of penalty. They are selected based
#' on the value of the violation matrix bigV. They are divided in 4 intervals that are [0,25], [0.25,0.5],
#' [0.5,0.75], [0.75,1]. The penalty for each interval is multiplied by 1,2,4 and 8 respectively
#' 
#' @param beta Static penalty parameter that will be multiplied to get the other
#' penalty coefficients
#' @param bigZ Matrix of scalarized objective values for each neighborhood and
#' the incumbent solution (generated by [scalarize_values()])
#' @param bigV Matrix of violation values for each neighborhood and the
#'
#' @return `[ N x (T+1) ]` matrix of preference indices. Each row `i` contains
#' a permutation of `{1, 2, ..., (T+1)}`, where `1,...,T` correspond
#' to the solutions contained in the neighborhood of the i-th subproblem,
#' `B[i, ]`, and `T+1` corresponds to the incumbent solution for that
#' subproblem. 


constraint_multistaged <- function(beta, bigZ, bigV, ...)
{
  # ========== Error catching and default value definitions
  assertthat::assert_that(
    identical(dim(bigZ), dim(bigV)))
  # ==========
  
  # Calculate the 4 multi-staged penalties
  K <- c(beta,beta*2,beta*4,beta*8)
  
  # Calculate penalized values in 4 equal intervals
  bigZV <- matrix(0,ncol=ncol(bigV),nrow = nrow(bigV))
  bigZV[which(bigV < 0.25)] = bigV[which(bigV < 0.25)]*K[1] + bigZ[which(bigV < 0.25)]
  bigZV[which(bigV >= 0.25 & bigV < 0.5)] = bigV[which(bigV >= 0.25 & bigV < 0.5)]*K[2] + bigZ[which(bigV >= 0.25 & bigV < 0.5)]
  bigZV[which(bigV >= 0.5 & bigV < 0.75)] = bigV[which(bigV >= 0.5 & bigV < 0.75)]*K[3] + bigZ[which(bigV >= 0.5 & bigV < 0.75)]
  bigZV[which(bigV >= 0.75)] = bigV[which(bigV >= 0.75)]*K[4] + bigZ[which(bigV >= 0.75)]
  
  # Get the selection matrix for all neighborhoods
  sel.indx <- t(apply(bigZV,
                      MARGIN = 2,
                      FUN    = order))
  
  return(sel.indx)
}